EarlyBookingService.MVC/Models/ErrorViewModel.cs
using System;

namespace EarlyBookingService.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EarlyBookingService.MVC/Controllers/AccomodationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EarlyBookingService.Lib.Models;
using EarlyBookingService.MVC.Helper;
using Microsoft.AspNetCore.Mvc;

namespace EarlyBookingService.MVC.Controllers
{
    public class AccomodationsController : Controller
    {
        string baseUri = "https://localhost:44396/api/Accomodation/";
        public IActionResult Index()
        {
            string conditionsUri = $"{baseUri}";
            return View(WebApiHelper.GetApiResult<List<Accomodation>>(conditionsUri));
        }
    }
}

EarlyBookingService.MVC/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EarlyBookingService.Lib.DTOs;
using EarlyBookingService.Lib.Models;
using EarlyBookingService.MVC.Helper;
using Microsoft.AspNetCore.Mvc;

namespace EarlyBookingService.MVC.Controllers
{
    
    public class BookingsController : Controller
    {
        string baseUri = "https://localhost:44396/api/PriceDetails/";
        public IActionResult Index(int id)
        {
            //string bookingsUri = $"{baseUri}/{id}";
            //return View(WebApiHelper.GetApiResult<List<PriceDetailBasic>>(bookingsUri));
            return View();
        }
    }
}

EarlyBookingService.MVC/Controllers/ConditionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EarlyBookingService.MVC.Helper;
using EarlyBookingService.Lib.Models;

namespace EarlyBookingService.MVC.Controllers
{
    public class ConditionsController : Controller
    {
        
        public IActionResult Index(int Id)
        {
            return View();
        }

    }
}

EarlyBookingService.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EarlyBookingService.MVC.Models;

namespace EarlyBookingService.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EarlyBookingService.MVC/Views/Accomodations/Index.cshtml
@using EarlyBookingService.Lib.Models
@model List<Accomodation>

<h1>Accomodations</h1>

<div class="row">
    <div class="col-md-4">
        <ul class="list-group">
            @foreach (Accomodation acco in Model)
            {
            <li class="list-group-item">
                <div>
                    <b><a href="#" data-id="@acco.Id" class="accomodation">@acco.Name</a></b>
                </div>
                <div>
                    <span><a asp-controller="Conditions" asp-action="Index" asp-route-id="@acco.Id"><i class="fas fa-search-plus"></i></a>Show conditions</span>
                </div>
            </li>
            }
        </ul>
    </div>
</div>

<!-- Bootstrap Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="myModalLabel">Accomodation detail:</h4>
            </div>
            <div class="modal-body">
                Details
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts
    {
    <script>
        $(document).ready(function () {
            var url = 'https://localhost:44396/api/Accomodation/';

            var infoModal = $('#myModal');
            $('.accomodation').on('click', function () {
                fetch(url + '/' + $(this).data('id'))
                    .then(response => response.json())
                    .then(function (accomodation) { showAccomodationDetail(accomodation); });
            });

            showAccomodationDetail = function (accomodation) {
                var htmlData = '<b>Name:</b> ' + accomodation.name + '<br \>';
                htmlData += '<b>Country:</b> ' + accomodation.country + '<br \>';
                htmlData += '<b>Email addres:</b> ' + accomodation.email + '<hr>';
                infoModal.find('.modal-body').html(htmlData);
                infoModal.modal('show');
            };
        });
    </script>

}

EarlyBookingService.MVC/Views/Bookings/Index.cshtml
@using EarlyBookingService.Lib.DTOs
@model List<PriceDetailBasic>

<h2>Early Booking List</h2>

<article id="app" class="row" v-cloak>
    <header class="col-md-4">
        <ul class="list-group">
            <li :class="getBookingClass(booking)" v-for="booking in bookings">
                {{ booking.bookingReservationNumber }} <a v-on:click="fetchBookingDetails(booking)"><i class="fas fa-info-circle"></i></a>
            </li>
        </ul>
    </header>
    <div v-if="selectedBooking" class="col-md-4">
        <h3>{{ selectedBooking.reservationNumber }}</h3>
        <div>
            <i class="fas fa-book"></i>
            <span>{{ selectedBooking.bookingDate }}</span>
        </div>
        <div>
            <i class="fas fa-plane-departure"></i>
            <span>{{ selectedBooking.startDate }}</span>
        </div>
        <div>
            <i class="fas fa-plane-arrival"></i>
            <span>{{ selectedBooking.endDate }}</span>
        </div>
        <div>
            <i class="fas fa-users"></i>
            <span>{{ selectedBooking.numberOfParticipants }}</span>
            <a v-on:click="fetchParticipantDetails(selectedBooking)"><i class="fas fa-search-plus"></i></a>
            <div v-if="participants">
                <ul class="list-group">
                    <li class="list-group-item" v-for="participant in participants">
                        <span>{{ participant.firstName }} </span>
                         
                        <span>{{ participant.lastName }} </span>
                    </li>
                </ul>
            </div>
        </div>
        <div>
            <i class="fas fa-coins"></i>
            <span>Purchase Cost</span>
            <a v-on:click="fetchPriceDetails(selectedBooking)"><i class="fas fa-search-plus"></i></a>
            <div v-if="priceDetails">
                <ul class="list-group">
                    <li class="list-group-item" v-for="priceDetail in priceDetails">
                        <span>{{ priceDetail.cost }} </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</article>

@section scripts
{
    <script src="~/js/vue.js"></script>
    <script>
        var apiURL = "https://localhost:44396/api/Bookings/Detail/";
        var bookingURL = "https://localhost:44396/api/PriceDetails/";
        var participantsURL = "https://localhost:44396/api/Participants/";
        var pricedetailsURL = "https://localhost:44396/api/PriceDetails/Booking/"

        var app = new Vue({
                el: '#app',
                data:
                {
                    bookings: null,
                    selectedBooking: null,
                    participants: null,
                    priceDetails: null,
                },
                created: function () {
                    var self = this;
                    self.fetchBooking(window.location.href.substr(window.location.href.lastIndexOf('/') + 1));
                },
            methods: {
                fetchBooking: function (id) {
                    self = this;
                    fetch(`${bookingURL}${id}`)
                        .then(res => res.json())
                        .then(function (bookings) {
                            bookings.forEach(function (booking, i) {
                                booking.isActive = false;
                            });
                            self.bookings = bookings;
                        })
                        .catch(err => console.error('Fout: ' + err));
                },
                fetchBookingDetails: function (booking) {
                    self = this;
                    fetch(`${apiURL}${booking.bookingId}`)
                        .then(res => res.json())
                        .then(function (res) {
                            self.selectedBooking = res;
                            self.makeBookingActive(booking.id);
                        })
                        .catch(err => console.error('Fout: ' + err));
                },
                fetchParticipantDetails: function (booking) {
                    self = this;
                    fetch(`${participantsURL}${booking.id}`)
                        .then(res => res.json())
                        .then(function (res) {
                            self.participants = res;
                        })
                        .catch(err => console.error('Fout: ' + err));
                },
                fetchPriceDetails: function (booking) {
                    self = this;
                    fetch(`${pricedetailsURL}${booking.id}`)
                        .then(res => res.json())
                        .then(function (res) {
                            self.priceDetails = res;
                        })
                        .catch(err => console.error('Fout: ' + err));
                },
                getBookingClass: function (booking) {
                    if (booking.isActive) return 'list-group-item active';
                    return 'list-group-item';
                },
                makeBookingActive: function (bookingid) {
                    self.bookings.forEach(function (booking, i) {
                        booking.isActive = booking.id === bookingid ? true : false;
                    });
                },
            }
        });
    </script>
}

EarlyBookingService.MVC/Views/Conditions/Index.cshtml
<h1>Early Booking Conditions</h1>

<article id="app" class="row" v-cloak>
    <header class="col-md-4">
        <h3 v-cloak>{{ message }}</h3>
        <nav>
            <ul class="list-group">
                <li v-for="condition in conditions" :class="getConditionClass(condition)">
                    <h4 v-cloak>{{ condition.accomodationName }} </h4>
                    <div class="bookingdate">
                        <i class="fas fa-book"></i>
                        <span v-cloak>{{ condition.bookingStartDate }}</span>
                        -
                        <span v-cloak :class="getEndDateClass(condition)">{{ condition.bookingEndDateString }}</span>
                    </div>
                    <div class="traveldate">
                        <i class="fas fa-plane-departure"></i>
                        <span v-cloak>{{ condition.reservationStartDate }}</span>
                        -
                        <span v-cloak>{{ condition.reservationEndDate }}</span>
                    </div>
                    <div class="ebpercentage">
                        <i class="fas fa-percent"></i>
                        <span v-cloak>{{ condition.amount }}</span>
                    </div>
                    <div class="prepayment">
                        <i class="far fa-credit-card"></i>
                        <span v-cloak v-if="condition.prepayment">
                            <span v-cloak>{{ condition.prepaymentPercentage }}</span>%
                            -
                            <span v-cloak>{{ condition.prepaymentDate}}</span>
                        </span>
                        <span v-cloak v-else>No prepayment</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-secondary" v-bind:href="'/Bookings/Index/' + condition.id "><i class="fas fa-search-plus"></i> Show bookings</a>
                        <a class="btn btn-primary" v-on:click="fetchPrepaymentDetails(condition)"><i class="fas fa-pencil-alt"></i> Edit prepayment</a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <div class="selectedCondition col-md-8">
        <span v-if="!currentCondition" class="placeholder">Please select a condition to be able to edit the prepayment details</span>
        <div v-if="currentCondition">
            <h3>Prepayment details</h3>
            <form>
                <div class="form-group">
                    <label class="control-label small"><i class="far fa-credit-card"></i> Prepayment %</label>
                    <input type="number" class="form-control" v-model="currentCondition.prepaymentPercentage" />
                </div>
                <div class="form-group">
                    <label class="control-label small"><i class="far fa-calendar"></i> Prepayment date</label>
                    <input type="datetime" class="form-control" v-model="currentCondition.prepaymentDate" />
                </div>
                <button v-on:click="save" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
 
</article>

@section scripts{
    
    <script src="~/js/vue.js"></script>
    <script>
        var apiURL = 'https://localhost:44396/api/PurchaseCost/';
        var app = new Vue({
            el: '#app',
            data: {
                message: 'Loading early booking conditions...',
                conditions: null,
                currentCondition: null,
            },
            created: function () {
                var self = this;
                self.fetchConditions(window.location.href.substr(window.location.href.lastIndexOf('/') + 1));
            },
            methods: {
                fetchConditions: function (id) {
                    self = this;
                    if (id == 0 || id == "0?") {
                        var URL = apiURL + "Details/"   
                    }
                    else {
                        var URL = apiURL + "Details/" + id
                    }
                    fetch(`${URL}`)
                        .then(res => res.json())
                        .then(function (conditions) {
                            conditions.forEach(function (condition, i) {
                                condition.isActive = false;
                                condition.prepayment = false;
                                if (condition.prepaymentPercentage > 0)
                                    condition.prepayment = true;
                            });
                            self.conditions = conditions;
                            self.message = '';
                        })
                        .catch(err => console.error('Fout: ' + err));

                },
                fetchPrepaymentDetails: function (condition) {
                    self = this;
                    fetch(`${apiURL}${condition.id}`)
                        .then(res => res.json())
                        .then(function (res) {
                            self.currentCondition = res;
                            self.makeConditionActive(condition.id);
                        })
                        .catch(err => console.error('Fout: ' + err));
                },
                getEndDateClass: function (condition) { //show that bookingenddate has passed so that list has to be validated
                    if (Date.parse(condition.bookingEndDate) < Date.now()) return 'end-date passed';
                    return 'end-date due';
                },
                getConditionClass: function (condition) {
                    if (condition.isActive) return 'list-group-item active';
                    return 'list-group-item';
                },
                makeConditionActive: function (conditionid) {
                    self.conditions.forEach(function (condition, i) {
                        condition.isActive = condition.id === conditionid ? true : false;
                    });
                },
                save: function () {
                    var self = this;

                    //self.currentCondition.accomodationId = self.currentCondition.accomodation.id;

                    var ajaxHeaders = new Headers();
                    ajaxHeaders.append("Content-Type", "application/json");
                    var ajaxConfig = {
                        method: 'PUT',
                        body: JSON.stringify(self.currentCondition),
                        headers: ajaxHeaders
                    };
                    let myRequest = new Request(`${apiURL}/${self.currentCondition.id}`, ajaxConfig);
                    fetch(myRequest)
                        .then(res => res.json())
                        .then(res => {
                            self.updateConditionList(res);
                        })
                        .catch(err => console.error('Fout: ' + err));
                },
                updateConditionList: function (condition) {
                    var updatedCondition = self.conditions.filter(c => c.id === condition.id)[0];
                    updatedCondition.title = condition.title;
                },
            }
        });
    </script>
}

EarlyBookingService.MVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EarlyBookingService.MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EarlyBookingService.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

EarlyBookingService.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EarlyBookingService.MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Early Booking Tool</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Accomodations" asp-action="Index">Accomodations</a></li>
                    <li><a asp-area="" asp-controller="Conditions" asp-action="Index" asp-route-id="0">Conditions</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EarlyBookingService.MVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>